INSERT INTO ciudad (nombre, paradas_de_metro, pais)
VALUES ('Madrid', 12, 'España'),
       ('Barcelona', 8, 'España'),
       ('Paris', 14, 'Francia'),
       ('Londres', 10, 'Reino Unido'),
       ('Nueva York', 24, 'EE. UU.'),
       ('Tokio', 9, 'Japón'),
       ('Roma', 11, 'Italia'),
       ('Sídney', 6, 'Australia'),
       ('Buenos Aires', 8, 'Argentina'),
       ('Moscú', 9, 'Rusia'),
       ('Estocolmo', 6, 'Suecia'),
       ('México D.F.', 13, 'México'),
       ('Lisboa', 4, 'Portugal'),
       ('Berlín', 12, 'Alemania'),
       ('Shanghái', 14, 'China'),
       ('Toronto', 5, 'Canadá'),
       ('Ámsterdam', 9, 'Países Bajos'),
       ('Dubái', 2, 'Emiratos Árabes Unidos'),
       ('Sao Paulo', 10, 'Brasil'),
       ('Seúl', 10, 'Corea del Sur');