version: '3.8'
services:
  web:
    build: /home/pi/ai2sql/app/
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - /home/pi/ai2sql/app/
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://ai2sql:ai2sql@db:5432/ai2sql
    depends_on:
      - dbwe
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=ai2sql
      - POSTGRES_PASSWORD=ai2sql
      - POSTGRES_DB=ai2sql

volumes:
  postgres_data: